name: 🐛 Bug 报告
description: 提交一个 Bug 报告以帮助我们改进
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        感谢您花时间填写这份 Bug 报告！请尽可能详细地填写以下信息，这将帮助我们更快地定位和解决问题。

  - type: input
    id: version
    attributes:
      label: 版本信息
      description: 您正在使用的 Nekro Agent 版本 (可在 WebUI 左上角 or 使用 `/na-info` 命令查看)
      placeholder: 例如：v0.7.0
    validations:
      required: true

  - type: dropdown
    id: deployment
    attributes:
      label: 部署方式
      description: 您使用的部署方式
      options:
        - Docker 一键部署（含 Napcat）
        - Docker 一键部署（不含协议端）
        - 手动部署
        - 其他
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: 运行环境
      description: 您的运行环境
      options:
        - Linux
        - MacOS
        - Windows + WSL
        - Windows + VM
        - Docker Desktop
        - 其他
    validations:
      required: true

  - type: dropdown
    id: arch
    attributes:
      label: 系统架构
      description: 您的系统架构
      options:
        - amd64 (x86_64)
        - arm64 (aarch64)
        - 其他
    validations:
      required: true

  - type: input
    id: python_version
    attributes:
      label: Python 版本
      description: 如果是手动部署，请提供 Python 版本
      placeholder: 例如：3.9.12

  - type: textarea
    id: what-happened
    attributes:
      label: 发生了什么？
      description: 请详细描述您遇到的问题
      placeholder: |
        1. 我做了什么...
        2. 然后发生了...
        3. 出现了错误...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 相关信息
      description: 请提供相关的 错误日志/截图/配置信息 (注意保护密钥等敏感信息)
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: 补充信息
      description: 还有什么其他信息需要补充的吗？
