name: Plugin Load Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-n-publish:
    name: Run Plugin Load Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.15"

      - name: Setup Poetry
        uses: pronovic/setup-poetry@v2
        with:
          version: "1.8.0"
          plugins: "poetry-dynamic-versioning==1.2.0"
          cache-venv: "true"
          cache-poetry: "true"

      - name: Install Dependencies
        run: >-
          poetry install

      - name: Plugin Load Test
        run: |
          poetry run bot --load-test
          if [ $? -ne 0 ]; then
            echo "Debug Mode Enabled"
            poetry run bot --load-test --verbose
          fi
