name: Plugin Load Test

on:
  push:
    branches:
      - main

jobs:
  build-n-publish:
    name: Run Plugin Load Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@main
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.16
      - name: Install Poetry
        run: >-
          curl -sSL https://install.python-poetry.org | python3 -
      - name: Install Dependencies
        run: >-
          poetry install
      - name: Plugin Load Test
        run: |
          poetry run bot --load-test
          if [ $? -ne 0 ]; then
            echo "Debug Mode Enabled"
            poetry run bot --load-test --verbose
          fi
