name: Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  setup-version:
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install toml
        run: pip install toml

      - name: Get Version
        id: get_version
        run: |
          VERSION=$(python3 -c 'import toml; print(toml.load("pyproject.toml")["tool"]["poetry"]["version"])')
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

  publish-to-pypi:
    name: Publish to PyPI
    runs-on: ubuntu-22.04
    needs: setup-version
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install Poetry
        uses: pronovic/setup-poetry@v2
        with:
          version: "1.8.0"
          plugins: "poetry-dynamic-versioning==1.2.0"
          cache-venv: true
          cache-poetry: true
      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi
      - name: Build package
        run: poetry build
      - name: Publish package
        run: poetry run publish
  build-and-push-images:
    name: Build and Push Docker Images
    runs-on: ubuntu-22.04
    needs: [setup-version, publish-to-pypi]
    strategy:
      matrix:
        target: [amd64, arm64]
        sandbox: [false, true]
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: image=moby/buildkit:v0.11.1-rootless
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push
        id: build-push
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.sandbox && './sandbox' || '.' }}
          file: ${{ matrix.sandbox && 'sandbox/Dockerfile' || 'Dockerfile' }}
          platforms: linux/${{ matrix.target }}
          push: true
          tags: |
            kromiose/nekro-agent${{ matrix.sandbox && '-sandbox' || '' }}:${{ needs.setup-version.outputs.version }}-${{ matrix.target }}
            kromiose/nekro-agent${{ matrix.sandbox && '-sandbox' || '' }}:latest-${{ matrix.target }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Docker Logout
        run: docker logout

  create-manifests:
    name: Create Multi-arch Manifests
    runs-on: ubuntu-22.04
    needs: [setup-version, build-and-push-images]
    strategy:
      matrix:
        sandbox: [false, true]
    steps:
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Create and Push Manifests
        run: |
          docker manifest create kromiose/nekro-agent${{ matrix.sandbox && '-sandbox' || '' }}:${{ needs.setup-version.outputs.version }} \
            kromiose/nekro-agent${{ matrix.sandbox && '-sandbox' || '' }}:${{ needs.setup-version.outputs.version }}-amd64 \
            kromiose/nekro-agent${{ matrix.sandbox && '-sandbox' || '' }}:${{ needs.setup-version.outputs.version }}-arm64
          docker manifest create kromiose/nekro-agent${{ matrix.sandbox && '-sandbox' || '' }}:latest \
            kromiose/nekro-agent${{ matrix.sandbox && '-sandbox' || '' }}:latest-amd64 \
            kromiose/nekro-agent${{ matrix.sandbox && '-sandbox' || '' }}:latest-arm64
          
          # 为每个架构添加注解
          docker manifest annotate kromiose/nekro-agent${{ matrix.sandbox && '-sandbox' || '' }}:${{ needs.setup-version.outputs.version }} \
            kromiose/nekro-agent${{ matrix.sandbox && '-sandbox' || '' }}:${{ needs.setup-version.outputs.version }}-amd64 --arch amd64
          docker manifest annotate kromiose/nekro-agent${{ matrix.sandbox && '-sandbox' || '' }}:${{ needs.setup-version.outputs.version }} \
            kromiose/nekro-agent${{ matrix.sandbox && '-sandbox' || '' }}:${{ needs.setup-version.outputs.version }}-arm64 --arch arm64
          docker manifest annotate kromiose/nekro-agent${{ matrix.sandbox && '-sandbox' || '' }}:latest \
            kromiose/nekro-agent${{ matrix.sandbox && '-sandbox' || '' }}:latest-amd64 --arch amd64
          docker manifest annotate kromiose/nekro-agent${{ matrix.sandbox && '-sandbox' || '' }}:latest \
            kromiose/nekro-agent${{ matrix.sandbox && '-sandbox' || '' }}:latest-arm64 --arch arm64
          
          # 推送 manifests
          docker manifest push kromiose/nekro-agent${{ matrix.sandbox && '-sandbox' || '' }}:${{ needs.setup-version.outputs.version }}
          docker manifest push kromiose/nekro-agent${{ matrix.sandbox && '-sandbox' || '' }}:latest
      - name: Docker Logout
        run: docker logout
