name: Publish to PyPI

on:
  push:
    tags:
      - v*.*.*

jobs:
  publish-to-pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.14
      - name: Install Poetry
        run: >-
          curl -sSL https://install.python-poetry.org | python3 -
      - name: Install Dependencies
        run: >-
          poetry install
      - name: PyPI Setup
        run: >-
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
      - name: Publish Package
        run: >-
          poetry run publish
  publish-app-image:
    name: Publish App Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: kromiose/nekro-agent:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
  # publish-sandbox-image:
  #   name: Publish Sandbox Image
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@master
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v1
  #     - name: Set up Docker Buildx
  #       id: buildx
  #       uses: docker/setup-buildx-action@v1
  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v1
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}
  #     - name: Enter Sandbox Directory
  #       run: >-
  #         cd sandbox
  #     - name: Build and Push Docker Image
  #       uses: docker/build-push-action@v2
  #       with:
  #         context: .
  #         file: Dockerfile
  #         push: true
  #         tags: kromiose/nekro-agent-sandbox:latest
  #         # cache-from: type=gha
  #         # cache-to: type=gha,mode=max
  #     - name: cleanup
  #       run: >-
  #         docker logout
